### ISSUE TITLE
System.NotSupportedException: Specified method is not supported.

### ISSUE THREAD

**Issue by sayago69** [rgvlee/EntityFrameworkCore.Testing#140]
Hello,

First of all, thank you for your library.

When testing a simple API action that is executing a stored proc against the database we're getting this error (including stack trace):

```
System.NotSupportedException: Specified method is not supported.
   at EntityFrameworkCore.Testing.Common.AsyncQueryProvider`1.CreateQuery[TElement](Expression expression)
   at Castle.Proxies.Invocations.AsyncQueryProvider`1_CreateQuery_1.InvokeMethodOnTarget()
   at Castle.DynamicProxy.AbstractInvocation.Proceed()
   at Moq.CastleProxyFactory.Invocation.ReturnBase()
   at Moq.Return.Handle(Invocation invocation, Mock mock)
   at Moq.Mock.Moq.IInterceptor.Intercept(Invocation invocation)
   at Castle.DynamicProxy.AbstractInvocation.Proceed()
   at Castle.Proxies.AsyncQueryProvider`1Proxy.CreateQuery[TElement](Expression expression)
   at MySystem.Api.Handler.MyAction.Handle(MyActionRequest request, CancellationToken cancellationToken) in C:\MyFolder\MySystem.Api\Handler\MyActionHandler.cs:line 65
``` 

The endpoint code we're trying to test looks like this, which is just processing the incoming data, calling our stored proc and returning error messages (if any):

```c#
public Task<MyActionResponse> Handle(MyActionRequest request, CancellationToken cancellationToken)
    {
        DataTable dataTable = new DataTable();

        dataTable.Columns.Add("myString", typeof(string));
        dataTable.Columns.Add("myDecimal", typeof(decimal));

        var myRows = request.MyList?.Select(m => (m.MyString, m.MyDecimal));
        if (myRows != null)
        {
            foreach (var row in myRows)
            {
                dataTable.Rows.Add(row.MyString, row.MyDecimal);
            }
        }

        var sqlParameter = new SqlParameter("spParameter", SqlDbType.Structured)
        {
            TypeName = "dbo.StructuredList",
            Value = dataTable
        };

        // Create the SQL command for executing the stored procedure
        var sqlCommand = "EXEC MyStoredProcedure @spParemeter";

        // Execute the stored procedure and get back the outcome
        var myResult = Context.MyEntity.FromSqlRaw(sqlCommand, sqlParameter).ToList();

        var resultData = _mapper.Map<List<MyErrorItem>>(myResult);

        // Return the list of errors in the response
        var response = new MyActionResponse
        {
            Data = resultData
        };

        return Task.FromResult(response);
    }
``` 

And the test we're trying to write looks like this:

```c#
[Fact]
public async Task MyTest()
{
    // Arrange
    var expectedResult = new List<MyEntity>
    {
        new MyEntity
        {
            ErrorMessage = "My Error Message",
            UserId = "123456"
        }
    };

    dbContext.Set<MyEntity>().AddFromSqlRawResult(expectedResult);

    var myActionRequest = new MyActionRequest 
    {
        MyList = new []
        {
            new MyListItem
            {
                MyString = "testString",
                MyDecimal = 12.3m
            }
        }
    };

    // Act
    var response = await _client.PostAsJsonAsync("myApiAction", myActionRequest, _serializerOptions);

    // Assert
    Assert.NotNull(response);
    Assert.Equal(HttpStatusCode.OK, response.StatusCode);
    // Some other asserts...
}
``` 

I think it is also worth mentioning that, since we're using structured data types from the database, we had to create the following keyless Entity for calling `MyStoredProcedure` (just in case):

```c#
namespace MySystem.Domain.Entity.Keyless;

[Keyless]
public class MyEntity
{
    public string UserId { get; set; }

    public string ErrorMessage { get; set; }
}
``` 

We're using Microsoft EF 6.0.16, EntityFrameworkCore.Testing.Moq 4.0.2 and .NET 6.

What are we doing wrong?

**Comment by sayago69** [comment]
Never mind.

We just found the issue: someone was creating twice the DBContext and using the wrong instance.
